### POSTTEST 2 KECERDASAN BUATAN
### Nama   : Wahyu Harry Saputra Sembiring
### NIM      : 2009106049
### Kelas   : Informatika A 2020

In [5]:
import pandas as pd
import numpy as np
from tabulate import tabulate
df = pd.read_csv("music_genre.csv")
df = df.iloc[:2500]

# Informasi yang didapatkan adalah jumlah record, nama attribute, jumlah attribute dengan tipe objek, jumlah attribute dengan tipe angka, jumlah attribute yang memiliki nilai null.

In [6]:
# Jmlah record
Jumlah = len(df)
print(Jumlah)

# nama atribut
nama = list(df.columns)
print(nama)

# jumlah atribut tipe objek
jumlahObjek = len(df.dtypes[df.dtypes == 'object'])
print(jumlahObjek)

# jumlah atribut tipe angka
jumlahInteger =len(df.dtypes[df.dtypes == 'int64'])
jumlahFloat =len(df.dtypes[df.dtypes == 'float64'])
jumlahAngka = jumlahInteger + jumlahFloat
print(jumlahAngka)

#jumlah atribut nilai null
df.isna().any().sum()

2500
['instance_id', 'artist_name', 'track_name', 'popularity', 'acousticness', 'danceability', 'duration_ms', 'energy', 'instrumentalness', 'key', 'liveness', 'loudness', 'mode', 'speechiness', 'tempo', 'obtained_date', 'valence', 'music_genre']
7
11

0

# Masukkan informasi di atas dalam dictionary dengan key sesuai nama informasinya. Tampilkan isi dari dictionary tersebut sebagus mungkin.

In [7]:
## Masukkan informasi di atas dalam dictionary dengan key sesuai nama informasinya. Tampilkan isi dari dictionary tersebut sebagus mungkin.

#Jumlah record
Jumlah = len(df)

#Nama Atribut
nama = list(df.columns)
nama = ",\n".join(nama)

# jumlah atribut tipe objek
jumlahObjek = len(df.dtypes[df.dtypes == 'object'])


# jumlah atribut tipe angka
jumlahAngka = len(df.dtypes[df.dtypes == 'int64'])

# jumlah atribut nilai null
jumlahNull = df.isna().any().sum()


kamus = {
    "Jumlah Record":[Jumlah],
    "Nama Atribut" : [nama],
    "Jumlah atribut tipe objek" : [jumlahObjek],
    "Jumlah atribut tipe angka" : [jumlahAngka],
    "Jumlah atribut nilai null"  : [jumlahNull],
    
}

tab = pd.DataFrame(kamus)
print(tabulate(tab, headers='keys', tablefmt='psql',showindex=False))

+-----------------+-------------------+-----------------------------+-----------------------------+-----------------------------+
|   Jumlah Record | Nama Atribut      |   Jumlah atribut tipe objek |   Jumlah atribut tipe angka |   Jumlah atribut nilai null |
|-----------------+-------------------+-----------------------------+-----------------------------+-----------------------------|
|            2500 | instance_id,      |                           7 |                           0 |                           0 |
|                 | artist_name,      |                             |                             |                             |
|                 | track_name,       |                             |                             |                             |
|                 | popularity,       |                             |                             |                             |
|                 | acousticness,     |                             |                             |                             |
|                 | danceability,     |                             |                             |                             |
|                 | duration_ms,      |                             |                             |                             |
|                 | energy,           |                             |                             |                             |
|                 | instrumentalness, |                             |                             |                             |
|                 | key,              |                             |                             |                             |
|                 | liveness,         |                             |                             |                             |
|                 | loudness,         |                             |                             |                             |
|                 | mode,             |                             |                             |                             |
|                 | speechiness,      |                             |                             |                             |
|                 | tempo,            |                             |                             |                             |
|                 | obtained_date,    |                             |                             |                             |
|                 | valence,          |                             |                             |                             |
|                 | music_genre       |                             |                             |                             |
+-----------------+-------------------+-----------------------------+-----------------------------+-----------------------------+

# Tampilkan rata-rata, standar deviasi, nilai minimum, nilai maksimum, Q1, Q2, dan Q3 dari attribute bertipe angka.

In [8]:
df.describe()

,instance_id,popularity,acousticness,danceability,duration_ms,energy,instrumentalness,liveness,loudness,speechiness,valence
count,2500.000000,2500.000000,2500.000000,2500.000000,2.500000e+03,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000
mean,55981.107600,38.330400,0.126405,0.618217,2.439299e+05,0.737214,0.337332,0.210038,-7.020556,0.098872,0.390466
std,20714.653342,9.841096,0.207015,0.148901,1.742257e+05,0.188890,0.361569,0.174656,3.706197,0.096395,0.238084
min,20005.000000,0.000000,0.000003,0.082200,-1.000000e+00,0.021100,0.000000,0.017300,-24.798000,0.023400,0.029500
25%,38081.500000,31.000000,0.004077,0.528750,1.922890e+05,0.611000,0.002465,0.096700,-9.313750,0.040500,0.194750
50%,55839.500000,37.000000,0.026850,0.629000,2.365675e+05,0.771000,0.143000,0.130500,-6.415000,0.058050,0.359000
75%,73842.250000,44.000000,0.145000,0.725000,2.999775e+05,0.898000,0.735250,0.285250,-4.319000,0.113000,0.557000
max,91744.000000,96.000000,0.985000,0.968000,4.830606e+06,0.998000,0.986000,0.959000,0.892000,0.648000,0.977000

# Tampilkan nilai korelasi attribute bertipe angka.

In [9]:
df.corr()

,instance_id,popularity,acousticness,danceability,duration_ms,energy,instrumentalness,liveness,loudness,speechiness,valence
instance_id,1.000000,-0.012872,0.025720,-0.009443,-0.047981,-0.037123,-0.001699,-0.014315,-0.025220,-0.024327,-0.001759
popularity,-0.012872,1.000000,0.032784,0.063408,0.025097,-0.040541,-0.078908,-0.044989,-0.001966,-0.089843,0.034680
acousticness,0.025720,0.032784,1.000000,-0.095263,0.051888,-0.548503,0.165422,-0.109017,-0.510429,-0.124053,-0.057839
danceability,-0.009443,0.063408,-0.095263,1.000000,0.004251,-0.022517,0.030801,-0.110775,-0.001357,0.039642,0.411831
duration_ms,-0.047981,0.025097,0.051888,0.004251,1.000000,-0.099696,0.153316,-0.032952,-0.163950,-0.070719,-0.028760
energy,-0.037123,-0.040541,-0.548503,-0.022517,-0.099696,1.000000,-0.195581,0.234627,0.764864,0.261162,0.116785
instrumentalness,-0.001699,-0.078908,0.165422,0.030801,0.153316,-0.195581,1.000000,-0.074993,-0.404106,-0.240305,-0.094529
liveness,-0.014315,-0.044989,-0.109017,-0.110775,-0.032952,0.234627,-0.074993,1.000000,0.180876,0.168254,-0.030621
loudness,-0.025220,-0.001966,-0.510429,-0.001357,-0.163950,0.764864,-0.404106,0.180876,1.000000,0.283300,0.053177
speechiness,-0.024327,-0.089843,-0.124053,0.039642,-0.070719,0.261162,-0.240305,0.168254,0.283300,1.000000,-0.007999
valence,-0.001759,0.034680,-0.057839,0.411831,-0.028760,0.116785,-0.094529,-0.030621,0.053177,-0.007999,1.000000

# Rubah nilai salah satu attribute bertipe angka menjadi desimal 3 angka dibelakang koma jika tidak ada, lakukan sebaliknya (dari desimal menjadi bilangan bulat).

In [11]:
df["energy"].dtypes
print(df["energy"].dtypes)

df["high"] = df["energy"].astype("int64")
print(df["energy"].dtypes)

float64
float64

# Tampilkan 10 record pertama dari attribute bertipe angka.

In [12]:
dfAngka= df.select_dtypes(include=['float64','int64'])

dfAngka.head(10)

,instance_id,popularity,acousticness,danceability,duration_ms,energy,instrumentalness,liveness,loudness,speechiness,valence,high
0,32894.0,27.0,0.00468,0.652,-1.0,0.941,0.792000,0.1150,-5.201,0.0748,0.759,0
1,46652.0,31.0,0.01270,0.622,218293.0,0.890,0.950000,0.1240,-7.043,0.0300,0.531,0
2,30097.0,28.0,0.00306,0.620,215613.0,0.755,0.011800,0.5340,-4.617,0.0345,0.333,0
3,62177.0,34.0,0.02540,0.774,166875.0,0.700,0.002530,0.1570,-4.498,0.2390,0.270,0
4,24907.0,32.0,0.00465,0.638,222369.0,0.587,0.909000,0.1570,-6.266,0.0413,0.323,0
5,89064.0,47.0,0.00523,0.755,519468.0,0.731,0.854000,0.2160,-10.517,0.0412,0.614,0
6,43760.0,46.0,0.02890,0.572,214408.0,0.803,0.000008,0.1060,-4.294,0.3510,0.230,0
7,30738.0,43.0,0.02970,0.809,416132.0,0.706,0.903000,0.0635,-9.339,0.0484,0.761,0
8,84950.0,39.0,0.00299,0.509,292800.0,0.921,0.000276,0.1780,-3.175,0.2680,0.273,0
9,56950.0,22.0,0.00934,0.578,204800.0,0.731,0.011200,0.1110,-7.091,0.1730,0.203,0

# Simpan dataset dengan attribute bertipe angka ke dalam file CSV.

In [14]:
dfAngka.to_csv("AtributAngka_Posttest2.csv", index=False)